### ISSUE TITLE
Deployment fails from time to time as the actions fails to find the function App

### ISSUE THREAD

**Issue by Michaelvsk** [Azure/functions-action#116]
Hi,
I am deploying a dotnet-isolated function app using .NET 6 and from time to time the deployment fails with the following error
```
Using RBAC for authentication, GitHub Action will perform resource validation.
##[debug]try-get AzureCLIAuthorizer
##[debug]"/usr/bin/az" account show
##[debug]"/usr/bin/az" cloud show
##[debug]"/usr/bin/az" account get-access-token
::add-mask::***
##[debug][GET] https://management.azure.com/subscriptions/***/resources?$filter=resourceType EQ 'Microsoft.Web%2FSites' AND name EQ '___FUNCTION__NAME___'&api-version=2016-07-01
Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)
Error:   Resource ___FUNCTION__NAME___ doesn't exist.
Error:     Error: Resource ___FUNCTION__NAME___ doesn't exist.
    at Function.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureResourceFilterUtility.js:21:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureResourceFilterUtility.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!
##[debug]Node Action run completed with exit code 1
```

I am using RBAC authentication via `azure/login@v1`. The service principal has contributor permission on the whole subscription.
When I use _Re-run all jobs_ for the workflow run, then deployment usually works fine.

I am deploying the function app via terraform, before deployment runs. But it also fails, if the function app is already there and exists for hours. So doesn't seem to be some kind of "race condition".

As I deploy IaC via terraform using publish-profiles would be overly complicated I would say. There seems to be no native support in terraform's azurerm to get the profile.

**Comment by jonas-lomholdt** [comment]
I'm also getting this. The function app is there, but it breaks during deployment

```
Error: Resource func-my-function doesn't exist.
    at Function.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureResourceFilterUtility.js:21:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureResourceFilterUtility.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jonas-lomholdt** [comment]
Redeploying it worked though. But then I hit the same issue in the next environment (test -> prod)

**Comment by Michaelvsk** [comment]
To bypass the issue I am querying the publish profile via az CLI for now. Here's an example:

```YAML
- uses: azure/login@v1
  with:
  creds: <CREDENTIALS>

- name: Retrieve publish profile for deployment
  id: publishProfileRetrieval
  run: |
    publishProfiles=$(az webapp deployment list-publishing-profiles \
      --name "<FUNCTION APP NAME>" \
      --resource-group "<RESOURCE GROUP NAME>" \
      --subscription "<SUBSCRIPTION ID>" --xml)
    echo "::add-mask::$publishProfiles"
    echo "::set-output name=publishProfiles::$publishProfiles"

- name: 'Run Azure Functions Action'
  uses: Azure/functions-action@v1
  with:
    app-name: <FUNCTION APP NAME>
    package: <PATH TO DEPLOYMENT PACKAGE>
    publish-profile: ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}
```

**Comment by Joaolfelicio** [comment]
Had the same issue, deleting the functions and re-running the pipeline did it, not the best solution in any case..

**Comment by Michaelvsk** [comment]
I am confused, too and don't understand why this issue has been closed. I do understand that the error seems to come from a library used here. But as long as the library isn't fixed and this action not upgraded to use the fixed version, I see no reason to close this bug.

I would even contribute to the library but there are PRs open since 2020 so I fear a patch wouldn't be picked up anytime soon. :/

**Comment by akbast** [comment]
@patelchandni any news on this?

**Comment by jannisrelakis** [comment]
This is still an issue. What about handling it instead of having the bots close it?

**Comment by jannisrelakis** [comment]
> To bypass the issue I am querying the publish profile via az CLI for now. Here's an example:
> 
> ```yaml
> - uses: azure/login@v1
>   with:
>   creds: <CREDENTIALS>
> 
> - name: Retrieve publish profile for deployment
>   id: publishProfileRetrieval
>   run: |
>     publishProfiles=$(az webapp deployment list-publishing-profiles \
>       --name "<FUNCTION APP NAME>" \
>       --resource-group "<RESOURCE GROUP NAME>" \
>       --subscription "<SUBSCRIPTION ID>" --xml)
>     echo "::add-mask::$publishProfiles"
>     echo "::set-output name=publishProfiles::$publishProfiles"
> 
> - name: 'Run Azure Functions Action'
>   uses: Azure/functions-action@v1
>   with:
>     app-name: <FUNCTION APP NAME>
>     package: <PATH TO DEPLOYMENT PACKAGE>
>     publish-profile: ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}
> ```

That didn't fix it for me. Thanks for the snippet though, I am using it regardless.

**Comment by reknih** [comment]
I'm experiencing this issue too (unidling)

**Comment by tjcorr** [comment]
> I am confused, too and don't understand why this issue has been closed. I do understand that the error seems to come from a library used here. But as long as the library isn't fixed and this action not upgraded to use the fixed version, I see no reason to close this bug.

Link to relevant issue: https://github.com/microsoft/pipelines-appservice-lib/issues/56

**Comment by JiayeHuang** [comment]
I have the same issue here

**Comment by KernelPryanic** [comment]
Wow, no movement since February, really?

**Comment by Gherdty** [comment]
I am experiencing the same issue currently with a freshly deployed function app

**Comment by oyvind3** [comment]
Seems very unstable, can't find a reason on why it fails pure randomley.

My github action workflow code:
`    - name: 'Run Azure Functions Action⚡'
      uses: Azure/functions-action@v1.1.6
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} 
        scm-do-build-during-deployment: true
        enable-oryx-build: true`

It returns -->

`Warning: Unexpected input(s) 'scm-do-build-during-deployment', 'enable-oryx-build', valid inputs are ['app-name', 'package', 'slot-name', 'publish-profile']
`
When I remove the "Unexpected Inputs" aka scm-do-build-during-deployment', 'enable-oryx-build', it does not get any better.

**However** one thing I found out about when running job azure/functions-action@v1.1.6, it does an API request that needs to match in order to find the functionappname, is there something I can go around to add a newer api verison.

Right before the error msg in action, the job does this **-->** ##[debug][GET] https://management.azure.com/subscriptions/***/resources?$filter=resourceType EQ 'Microsoft.Web%2FSites' AND name EQ 'functionappname'&api-version=**2016-07-01**

So API version of functionapp needs to be 2016-07.01. I see in the function resource: resource function 'Microsoft.Web/sites/functions@2016-08-01' that 2016-08-01 is available.

When I try API version 2016-08-01 of function app, it also failed...

**Comment by oyvind3** [comment]
For sure is some issue related to the Azure/functions-action@v1

**Comment by oyvind3** [comment]
@patelchandni thanks for your input here! I first started with the V1, but experienced similar issue. Changed back to `Azure/functions-action@v1` again now, and in debug mode it says the same: 
![chrome_XWexe9x9K8](https://user-images.githubusercontent.com/71570586/215988229-c561b63f-78ca-493a-9cd8-ee277cf5c7ce.png)

In Azure portal: 
![OUTLOOK_49BrAmwexw](https://user-images.githubusercontent.com/71570586/215989051-c2486867-38a4-48a0-a01e-ef080db83872.png)

The frustrating part is that the whole GitHub action does everything regarding my deployment, everything in Azure is deployed the way I wanted it.

It's hard to find the root cause of my issue since it's working, but at the same time not🤷‍♂️

**Comment by Jtango18** [comment]
Same issue here. Interestingly when I run the query that the action uses from the management REST API, it does not list the function in the available resources either, which makes the think this is not an issue with the action, but something else going on elsewhere?

**Comment by Joey40** [comment]
Same issue here.  Based on some of the comments here I just kept re-running the action.  The 4th or 5th time it worked.  Pretty frustrating.  The equivalent task in Azure Pipelines works without any issues.

**Comment by Jtango18** [comment]
I have a Support Ticket open with Azure Support around this. Looks like an ARM sync issue. Good news is they can replicate it, will keep this thread updated as I hear more.

**Comment by wbcapt** [comment]
Thank you @Jtango18 !! Anything yet?

I'm also on ARM

**Comment by Jtango18** [comment]
It's no longer repeatable from me after some changes by the support/ARM team. Can't state with 100% certainty that it's resolved. But works on my machine now 🤷‍♂️

**Comment by runeheidem** [comment]
> To bypass the issue I am querying the publish profile via az CLI for now. Here's an example:
> 
> ```yaml
> - uses: azure/login@v1
>   with:
>   creds: <CREDENTIALS>
> 
> - name: Retrieve publish profile for deployment
>   id: publishProfileRetrieval
>   run: |
>     publishProfiles=$(az webapp deployment list-publishing-profiles \
>       --name "<FUNCTION APP NAME>" \
>       --resource-group "<RESOURCE GROUP NAME>" \
>       --subscription "<SUBSCRIPTION ID>" --xml)
>     echo "::add-mask::$publishProfiles"
>     echo "::set-output name=publishProfiles::$publishProfiles"
> 
> - name: 'Run Azure Functions Action'
>   uses: Azure/functions-action@v1
>   with:
>     app-name: <FUNCTION APP NAME>
>     package: <PATH TO DEPLOYMENT PACKAGE>
>     publish-profile: ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}
> ```

Had similar issue with azure/webapps-deploy@v2 and by accident caused by frustrations ended up with the same solution.

**Comment by kaluzaaa** [comment]
Any news about this?

**Comment by tspascoal** [comment]
I can confirm this also happens with a function app created with Bicep (haven't yet figured out what unblocks it)

**Comment by dvegaeygds** [comment]
I'm getting a similar error with @v1 or @v1.4.3, 1.4.5 etc. 
with this:
`      env:
       AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 

       - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1.4.6
        id: deploy-to-function
        with:
          app-name: 'B14B1-function-main'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}`

any idea?

![image](https://user-images.githubusercontent.com/127428374/233762902-36a512c8-0684-4ee6-89f9-380f3834ec5f.png)

**Comment by fleed** [comment]
Same problem here

**Comment by ranrsg** [comment]
Same here.
In our case I see it is working just fine for existing function apps - but newly created ones are getting this 'Execution Exception (state: ValidateAzureResource) (step: Invocation)' and 'Resource ___FUNCTION__NAME___ doesn't exist' for almost one hour until it is finely working..

**Comment by aluczak** [comment]
In my case the issue is caused by a breaking change introduced in Terraform 0.14 mentioned in the following issue https://github.com/hashicorp/terraform/issues/27100. In line 7776 on the below screenshot there is the exact URL called from within the functions action and there are additional encoded quotation marks in the function app name
![image](https://github.com/Azure/functions-action/assets/11255064/e67ccdfe-99b6-4e92-ab3b-b33cf30505e7)
I called the same URL using postman and the resource is not returned which is the direct reason for the failure.

**Comment by bachar-senno** [comment]
Same issue here. It was working couple of days ago, and now suddenly, resource doesn't exist. Not sure where to go from here. Anyone found a viable solution:

I tried passing the publish profile as suggested, it no longer says resource doesn't exist, but I still am unable to find my functions in my function app after it finishes.

**Comment by BenjaminNiemann** [comment]
Same issue here with a new azure function. Created the function yesterday and now the same issue. This -> https://learn.microsoft.com/en-us/troubleshoot/azure/devops/resource-not-exist-error-services-deployment cant be the solution, because of the delay the function was created a day before. Is use a managed idenitiy to deploy. May permissons are not set?

**Comment by skvark** [comment]
Same issue here too...

**Comment by rbourdon** [comment]
I experienced this while setting up CD for an existing function app **slot**, using the generated workflow file. I used the token retrieved in the azure/login action (using the managed identity azure generated) to call the endpoint that the azure/functions-action calls and confirmed the response was an empty array. After I gave the generated managed identity the Website.Contributor role for the main function app (in addition to the slot), deployment succeeded.

**Comment by patelchandni** [comment]
released https://github.com/Azure/functions-action/releases/tag/v1.5.3 with the fix
