### ISSUE TITLE
Deploying with `publish-profile` from `github secrets` errors with `No credentails found`

### ISSUE THREAD

**Issue by levincalado** [Azure/functions-action#189]
Hello,

I'm currently using this github action and I followed all the instructions as instructed with [Using Publish Profile as Deployment Credential (recommended)](https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended).

I've downloaded the `.PublishSettings` and put it on `github secrets` but I'm encountering this error below:
```
Using RBAC for authentication, GitHub Action will perform resource validation.
Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)
Error:   No credentails found. Add an Azure login action before this action. For more details refer https://github.com/azure/login
Error:     Error: No credentails found. Add an Azure login action before this action. For more details refer https://github.com/azure/login
    at Function.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-webclient/AuthorizerFactory.js:23:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-webclient/AuthorizerFactory.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Deployment Failed!
```

i'm also doing remote build and set the following parameters needed to true. see sample below:

```yaml
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}-${{ github.event.inputs.environment }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
```

**Comment by levincalado** [comment]
oh sorry it's my mistake for a missing `env` value. will close this now.
