### ISSUE TITLE
Error in run azure/functions-action@v1

### ISSUE THREAD

**Issue by BrunaCelestino** [Azure/functions-action#203]
When deploying it, I had the following error:

Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)

Error:   When request Azure resource at ValidateAzureResource, Get Function App Settings : Failed to acquire app settings from https://<scmsite>/api/settings with publish-profile

Error:     Failed to fetch Kudu App Settings.

Service Unavailable (CODE: 503)

Error:       Error: Failed to fetch Kudu App Settings.

Service Unavailable (CODE: 503)

    at Kudu.<anonymous> (/__w/_actions/azure/functions-action/v1/lib/appservice-rest/Kudu/azure-app-kudu-service.js:69:23)

    at Generator.next (<anonymous>)

    at fulfilled (/__w/_actions/azure/functions-action/v1/lib/appservice-rest/Kudu/azure-app-kudu-service.js:5:58)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: Deployment Failed!

 

Any idea how to solve this?

**Comment by patelchandni** [comment]
@BrunaCelestino we will need app details and logs to further investigate this type of issues. So, please open a support ticket from azure portal if this issue still persists.
