### ISSUE TITLE
Unable to deploy function app with RBAC

### ISSUE THREAD

**Issue by xl1** [Azure/functions-action#48]
I had trouble deploying a function app using a service principal. The latest `Azure/functions-action@v1` seems to always use SCM credentials, even if no publish profile is specified.

Logs:
```
2020-11-15T05:00:31.7682000Z ##[group]Run Azure/functions-action@v1
2020-11-15T05:00:31.7682891Z with:
2020-11-15T05:00:31.7683719Z   app-name: ***
2020-11-15T05:00:31.7684604Z   package: ***
~~~
2020-11-15T05:00:31.7692175Z ##[endgroup]
2020-11-15T05:00:32.2293298Z ##[Initialize]
2020-11-15T05:00:32.2352987Z ##[ValidateParameter]
2020-11-15T05:00:32.2370259Z ##[ValidateAzureResource]
2020-11-15T05:00:32.2376919Z Using SCM credential for authentication, GitHub Action will not perform resource validation.
2020-11-15T05:00:32.3097967Z ##[error]Execution Exception (state: ValidateAzureResource) (step: Invocation)
2020-11-15T05:00:32.3116888Z ##[error]  When request Azure resource at ValidateAzureResource, Get Function App Settings : Failed to acquire app settings (SCM)
2020-11-15T05:00:32.3120900Z ##[error]    Failed to fetch Kudu App Settings.
Bad Request (CODE: 400)
2020-11-15T05:00:32.3130134Z ##[error]      Error: Failed to fetch Kudu App Settings.
Bad Request (CODE: 400)
    at Kudu.<anonymous> (D:\a\_actions\Azure\functions-action\v1\node_modules\azure-actions-appservice-rest\Kudu\azure-app-kudu-service.js:62:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\Azure\functions-action\v1\node_modules\azure-actions-appservice-rest\Kudu\azure-app-kudu-service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-11-15T05:00:32.3138642Z ##[error]Deployment Failed!
```

I think this `creds` was changed to a non-null value recently
https://github.com/Azure/functions-action/blob/31d8bb80f65baebccb7de71a651962769aefccd9/src/handlers/parameterValidator.ts#L58-L61
and then `context.authenticationType` is always `Scm`.
https://github.com/Azure/functions-action/blob/31d8bb80f65baebccb7de71a651962769aefccd9/src/handlers/parameterValidator.ts#L53

I'm using `Azure/functions-action@v1.1.6` for now and it's working.

**Comment by plamber** [comment]
Hello,
experience a similar issue when specifying the slot-name parameter. I am getting following error message

![image](https://user-images.githubusercontent.com/18241305/99178907-72950800-2718-11eb-9d60-d572720cc160.png)

The suggestion of @xl1 of using Azure/functions-action@v1.1.6 seems to be a viable workaround for now.

br,
Patrick

**Comment by Hazhzeng** [comment]
Hi @xl1,

I'm looking into the issue now, please pin back to a previous version as mitigation for now (e.g. AzureFunctions@v1.1.6)

**Comment by Hazhzeng** [comment]
Hi @xl1,

I've released a new version to address this issue and updated the v1 tag https://github.com/Azure/functions-action/releases/tag/v1.1.8. Please check if the issue is fixed on your side, and thanks for your detailed analysis.

**Comment by xl1** [comment]
I tested it in my repository and confirmed that the issue was fixed. Thank you for your quick response.
